### PR TITLE
fix: pr label longer than 50 characters not allowed on github

### PR DESCRIPTION
**Pull request by bagutzu**
Signed-off-by: Raul Bag <raulbag1996@gmail.com>

### CODE REVIEW

**Comment by bagutzu** [comment]
Hi. Would it be possible to get the error logs? Tests passed locally. Thanks !

/cc @msvticket

**Comment by msvticket** [comment]
> Hi. Would it be possible to get the error logs? Tests passed locally. Thanks !

For me `make test` fails.
Here you are:


		--- FAIL: TestPromoteIntegrationHelmfile (0.03s)
		panic: runtime error: slice bounds out of range [:49] with length 14 [recovered]
			panic: runtime error: slice bounds out of range [:49] with length 14

**Comment by bagutzu** [comment]
Thank you ! Fixed, updated, rebased and squashed.

The lint failure the jxbot mentions was also fixed.

/cc @msvticket

**Pull request merged**
